sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  except:
  - gh-pages
addons:
  firefox: "latest"
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
before_script:
- npm install web-component-tester
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- xvfb-run wct --skip-plugin sauce
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then wct --plugin sauce --skip-plugin
  local; fi
env:
  global:
  - secure: Qy3G59t1yRK1+1XcW+pG2SSu3VjTFjyD3kaHFUnK/7ZW4PFVVUQPzvWGjPUe8XZ76tiTFB7AMD+5zwqETki3GrtjpUKwoXQ6jRFOU7qw+oF+UKuw77T3AyVGXOKP/BdVQh1PyoWrJsCx7rxl7Z6PBZgN96cG+7pq89YJ445rJULa01Eu+kPFnWXqyRO5snhv68+2H1BTg7O+H1PsYfyXGTpsA7F4TBNuzQHaWm2bV5DWEdURxufcW20EY7yPJfrni4ARve5AFmo4gRoc3q10W36/IyJNw5Biv1mBsrD0zPFFpcpMuSmLNa9Ndh5YrDl8/kS3pLYL5aBkytG18pxthuu0dUmGk2J9vsnkbtssXZN8R/QkzRRuen1GJ8vlzpcyFvRueVEKmJk0EjJjh8zpjuqQ1lQrY2C6MCIB7FbXb/a0eVbBAtKFsT7qDV5sYhhTiMSA+80l66HtSkTUDk0DmxJDdBJsMfcMGpsfmXIDNPOaYUd1lcAp+uEVfZmyoicY43677ivJPxI1DAtVETIxsCObTm4RKSwdZtleZC7xdEVuhi8eZUXF643zkip3V7QdpwuYOth7DqsW0yIZRHXQCLKaLy5InMLuteovbHbW+Ss+c1CycyL7xYp8Zbwaew0EdfEAFZO6RoCfut/R8qbWyajDuGpXXgEC6Dh8SE3/k2E=
  - secure: GtpW1/7Cqv8znuaS/3CFk5e6Rp4XpV/qHzCa+7RDaHdXnM+oyRXlM3NMEnX3eaHHRsw7cX8vRzPdDEO6xZw1L+tpxpGbECSaH+5mZcFSPXjbvwCSBBFtk4aLznic7cmiBg0vFXv62UgGorAfYIi7GFEu0nicYVK6rjWz+ueYBbVyTr+XB+/KkQUS/ZFLbUNJwoNwwwSiXygTOjDRrj73W8+7TY/kDGXnj0M6n07O0Z5z9imEQWcYDJvcGtg8LLMBr/UfR4sIqPDywE5dEqyabkoLlOumL9ZxomPLEq2Ue5R4vH4DVqPe60v64N9xsJVYSbsduhyAftdlpjYU6wNcJZ1Gljs/k0JacblEIzQ7TSp/zwjy/RqlaUBY6AoQjZ7prpCqc/H0PdiTHrtfCkrhWE9l1GfXIq0WvB4ZAtcTw0qu2WNWJyWTMMhkYO9KP0GcCFWI91KHCy8fFgO7LlLBCj/TwEVLGfDinb0Aj+hcTalMIqgNoAFjl/jngVBdT38P/YcTlQZVBVvBogwIDc3E7ATz+KsfCIgY31MgkkA8SxNFwN3YNO2aOzpHaIez+BGVcHzIaEhaS+SQWjmk5Vt1MbaEXivZSXyPEyAHju3EPCxr5uRxQMuLn7+ykI1exhI/tYKkyZ1omjUFwdyo1Hyy0HmARaPMp3V91HSQlDek3KU=
before_install:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$password"
  -in id_rsa.enc -out deploy_key -d; fi
after_success:
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- "./ghp.sh"
